spring.application.name=cafe-lab

spring.datasource.url=jdbc:sqlserver://monolito-funda-server.database.windows.net:1433;database=monolito-funda-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# SQL Server Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.naming.physical-strategy=com.cafemetrix.cafelab.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
# Application Information for Documentation
# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@
# JWT Configuration Properties
authorization.jwt.secret=${JWT_SECRET:CafeLabLocalDevSecretKey2026MinimumLength32Chars}
authorization.jwt.expiration.days = 7
# Flyway Configuration
spring.flyway.enabled=false